# Generated by Django 4.1 on 2022-08-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_position_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_code',
        ),
        migrations.AddField(
            model_name='position',
            name='user_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Код'),
        ),
    ]
