# Generated by Django 4.1 on 2022-08-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_remove_person_user_code_position_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='user_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Код'),
        ),
    ]
