# Generated by Django 4.1 on 2022-08-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_director_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativebody',
            name='collegial_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_bodies', to='structure.collegialbody'),
        ),
        migrations.AlterField(
            model_name='collegialbody',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='collegial_bodies', to='structure.organization'),
        ),
        migrations.AlterField(
            model_name='director',
            name='administrative_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='structure.administrativebody'),
        ),
        migrations.AlterField(
            model_name='director',
            name='collegial_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='structure.collegialbody'),
        ),
        migrations.AlterField(
            model_name='director',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='structure.subdivision'),
        ),
        migrations.AlterField(
            model_name='person',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='structure.director'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons', to='structure.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='administrative_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='structure.administrativebody'),
        ),
        migrations.AlterField(
            model_name='position',
            name='collegial_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='structure.collegialbody'),
        ),
        migrations.AlterField(
            model_name='position',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='structure.director'),
        ),
        migrations.AlterField(
            model_name='position',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='structure.subdivision'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='structure.director'),
        ),
    ]
