# Generated by Django 4.1 on 2022-08-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='director',
            new_name='person',
        ),
    ]
