# Generated by Django 4.1 on 2022-08-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_rename_director_task_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_start'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField( max_length=1000, verbose_name='Описание задачи'),
        ),
    ]
